# Generated by Django 5.2.15 on 2026-07-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='試合日')),
                ('opponent', models.CharField(max_length=100, verbose_name='対戦相手')),
                ('tournament', models.CharField(max_length=200, verbose_name='大会名')),
                ('japan_score', models.IntegerField(verbose_name='日本得点')),
                ('opponent_score', models.IntegerField(verbose_name='相手得点')),
                ('result', models.CharField(choices=[('W', '勝ち'), ('D', '引き分け'), ('L', '負け')], max_length=1, verbose_name='勝敗')),
                ('venue', models.CharField(max_length=200, verbose_name='開催地')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='監督')),
                ('scorers', models.TextField(blank=True, help_text='カンマや改行区切りで入力してください', null=True, verbose_name='得点者')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='メモ/詳細')),
            ],
            options={
                'verbose_name': '戦績',
                'verbose_name_plural': '戦績一覧',
                'ordering': ['-date'],
            },
        ),
    ]
